### PR TITLE
feat: adding ``pyansys-sound``

### PR DESCRIPTION
**Pull request by clatapie**
Adding ``pyansys-sound`` to the PyAnsys metapackage.

### CODE REVIEW

**Review by RobPasMue — CHANGES_REQUESTED** [review]
Incompatible with the rest of the packages. Please fix this

**Comment by greschd** [comment]
It seems `pyansys-sound` needs to support older versions of `platformdirs`. Longer-term, though, `ansys-fluent-core` may also need to lift this restriction (if it's even a real incompatibility): 

```
ansys-fluent-core 0.21.2 depends on platformdirs<4.0.0 and >=3.5.1
```

**Comment by RobPasMue** [comment]
> It seems `pyansys-sound` needs to support older versions of `platformdirs`. Longer-term, though, `ansys-fluent-core` may also need to lift this restriction (if it's even a real incompatibility):
> 
> ```
> ansys-fluent-core 0.21.2 depends on platformdirs<4.0.0 and >=3.5.1
> ```

I completly agree... unless it's a real restriction on PyFluent they should make it more flexible

**Comment by greschd** [comment]
Pinging @mkundu1 for visibility.

**Comment by mkundu1** [comment]
What should be the supported version range for platformdirs? I see most repos are using >=3.6: https://github.com/search?q=org%3Aansys+platformdirs+language%3ATOML&type=code&l=TOML

**Comment by mkundu1** [comment]
Fixed in pyfluent version [0.21.3](https://pypi.org/project/ansys-fluent-core/0.21.3/)

**Review by RobPasMue — APPROVED** [review]
Issue solved - LGTM

**Pull request merged**
