### PR TITLE
fix: revert the page cards to align left

### PR DESCRIPTION
**Pull request by Revathyvenugopal162**

### CODE REVIEW

**Comment by MaxJPRey** [comment]
Both works for me: left aligned or centered.

**Comment by RobPasMue** [comment]
@ansys/pyansys-core please upvote or downvote to see whether you want this PR merged or not. I will leave it up for 2 weeks. @Revathyvenugopal162 please share with the docs team as well.

**Comment by RobPasMue** [comment]
> @ansys/pyansys-core please upvote or downvote to see whether you want this PR merged or not. I will leave it up for 2 weeks. @Revathyvenugopal162 please share with the docs team as well. Use the emojis I added for this

Hey @ansys/pyansys-core I'd appreciate some more inputs here...

Also @ansys/documentation would you also vote if possible?

**Comment by nshum4** [comment]
@RobPasMue Can I rerun the jobs to see the artifacts (documentation html build)? The original ones expired.

**Comment by RobPasMue** [comment]
Given the results of the voting - I am merging this PR. Thank you all!

**Review by RobPasMue — APPROVED** [review]

**Pull request merged**
