### PR TITLE
Update PyGranta to 2024.2.0

### PR DESCRIPTION
**Pull request by Andy-Grigg**
Update PyGranta to 2024.2.0. This will need to be cherry-picked onto the 2024.2 release branch before release.

Also remove dependency on ansys-openapi-common, since in my opinion this is an unneeded constraint. I think currently only PyGranta packages include this, and if any other packages include it, they should declare it as a dependency themselves.

@klmcadams Adding you as a reviewer since you were suggested by GitHub.

### CODE REVIEW

**Review by RobPasMue — APPROVED** [review]

**Review by RobPasMue — CHANGES_REQUESTED** [review]
Why are we removing the openapi-common?

**Comment by Andy-Grigg** [comment]
> Why are we removing the openapi-common?

It's only a transitive dependency of pygranta. It's not used directly, it just provides transport and authentication for packages that use the swagger-codegen code generator library that we wrote for Python. The version of openapi-common that's used is determined by the versions of pygranta packages that are installed, it's never something that a user will select directly.

**Comment by RobPasMue** [comment]
> It's only a transitive dependency of pygranta. It's not used directly, it just provides transport and authentication for packages that use the swagger-codegen code generator library that we wrote for Python. The version of openapi-common that's used is determined by the versions of pygranta packages that are installed, it's never something that a user will select directly.

That I have checked and it is true - I see that only the granta packages are consuming it.

> I'd argue it's more similar to `requests` than a real PyAnsys package.

However, we are also providing "tool" packages as part of the metapackage. And this is the case for the openapi-common package. See others here: https://docs.pyansys.com/version/dev/tools/libraries/index.html - that is why the openapi-common package also gets delivered. It is part of the "Shared components" section and it could be consumed by other packages.

Unless it is really bothering you or you really want to get it removed from the docs and the metapackage as a direct dependency I would suggest we leave it there and update the version (for some reason it doesn't seem to be updated - let me do that)

Do you agree @Andy-Grigg? Or do you prefer to completely remove its references from the metapackage? I think it is a valuable package on its own nonetheless. But since you are the ones maintaining it, I will leave the decision to all of you.

**Comment by RobPasMue** [comment]
Okay we will leave it in the docs but remove it from the install - let me check out your branch one sec (we need to do some extra mods). Thanks for your answer!

**Review by RobPasMue — APPROVED** [review]

**Pull request merged**
