### PR TITLE
fix: ansys-fluent-core version

### PR DESCRIPTION
**Pull request by vgelbgras**
ansys-fluent-core 0.21.1 does not exist, set the version to 0.21.0

### CODE REVIEW

**Comment by mayur-lankeshwar** [comment]
Hi @AlejandroFernandezLuces  @RobPasMue @clatapie  can this be approved please? This is blocker for us causing CI actions to fail across all of our SAF repos disabling us to produce any releases that are waiting for customer delivery in next week.

**Review by AlejandroFernandezLuces — APPROVED** [review]

**Comment by AlejandroFernandezLuces** [comment]
I wonder why we had that version there... Was this dependency manually updated?

**Comment by AlejandroFernandezLuces** [comment]
This is the commit where it was bumped: https://github.com/ansys/pyansys/commit/f7dfb69ac22b94e3ec84579e5b44287d2e430885

I guess this was just a mistake? @RobPasMue

**Comment by RobPasMue** [comment]
Not a mistake. Fluent team was supposed to release it yesterday. Thanks for ioxing it

**Comment by RobPasMue** [comment]
They had problems when releasing... Should be fixed soon

**Comment by RobPasMue** [comment]
Nonetheless @vgelbgras - is there a reason why you are not using the released version rather than the "main" branch?

**Pull request merged**
